### ISSUE TITLE
Isolate channel logic in a `channel.qnt` spec

### ISSUE THREAD

**Issue by bugarela** [informalsystems/apalache-team-services#7]
The reference implementation has a channel keeper (like the bank keeper). I think we also want something like that since handling channels has been a pain.

**Comment by thpani** [comment]
Related: the packet fields in `ChainState` currently cause some confusion (https://github.com/informalsystems/quint/pull/865#discussion_r1187323389)

If we want to be entirely truthful to the implementation, we would have only `outPackets` and `inAcknowledgements` in `ChainState`, and the remaining relayer magic is kept in the stateful part of the spec, or another module.

This would duplicate some state between `ChainState` and the relayer-related state, so we should check with @josef-widder how far we want to take this idea.

**Comment by josef-widder** [comment]
I am not sure I totally understand the question: are we discussing whether/how we should write a spec that, e.g., makes sure a packet sent is received or generates a timeout?

**Comment by thpani** [comment]
No, this issue is more of a refactoring: Currently the relaying logic is hidden/spread across the `ChainState` type, and the various actions.

I think there would be a cleaner way to do it, by isolating all the channel/relayer logic into a separate module. But also that adds more code, and that is probably detrimental to understanding ICS 20.

**Comment by bugarela** [comment]
We have made some nice improvements on channel topology manipulation inside the specs after I opened this issue. I'm not sure if it makes sense anymore.
